# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build
      working-directory: workshop-service
      run: go build -v ./...

    - name: Upload /bin folder as artifact
      uses: actions/upload-artifact@v3
      with:
        name: workshop
        path: bin/
        retention-days: 1

    # Docker container steps
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKER_ACCESTOKEN}}
    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: /aelm-workshop-23
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
